### ISSUE TITLE
Allow change of background window

### ISSUE THREAD

**Issue by VandeWalleUriah** [ZamanKwinten/jlogg#3]
On Mac I'm using the Dark Theme, so most of my apps are black/grey background with white text.
Opening up JLogg feels like someone is pointing a flashlight into my eyes ;)

(I guess I could tweak the filters to already to this, but having a default setting would be awesome)

<img width="1677" alt="Difference_JLoggvsBBEdit" src="https://user-images.githubusercontent.com/79696935/109484836-3300ea80-7a81-11eb-8448-0651283b9649.png">

**Comment by ZamanKwinten** [comment]
The latest version will now have a partial support for a Dark theme, the main UI is already converted the popups (filter menu, preferences, ...) still need to be converted

**Comment by ZamanKwinten** [comment]
Dark theme is now fully supported in all windows/popups + some general UI/CSS fixes
